[theme]
background = "#101010"
primary = "#C5C8C6"
secondary = "#DCDCDC"
title = "#6A7C93"
playing = "#6A7C93"
playing_selected = "#6A7C93"
playing_bg = "#282A2E"
highlight = "#282A2E"
highlight_bg = "#6A7C93"
error = "#FFE4E4"
error_bg = "#CC6666"
statusbar = "#282A2E"
statusbar_progress = "#6A7C93"
statusbar_bg = "#6A7C93"
cmdline = "#5E8D87"
cmdline_bg = "#373B41"
