[theme]
background = "#181818"
primary = "#C5C8C6"
secondary = "#DCDCDC"
title = "#7A7C57"
playing = "#7A7C57"
playing_selected = "#151515"
playing_bg = "#282A2E"
highlight = "#282A2E"
highlight_bg = "#7A7C57"
error = "#FFE4E4"
error_bg = "#CC6666"
statusbar = "#282A2E"
statusbar_progress = "#7A7C57"
statusbar_bg = "#7A7C57"
cmdline = "#5E8D87"
cmdline_bg = "#373B41"
